name: "Boura Lab @ UVA"
description: "This is the official web page for the Phil Bourne and Cam Mura's lab at UVA."

url: "http://bournelab.org"

paginate: 5
gems: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown: 
  parse_block_html: true
